### ISSUE TITLE
Feature request: Make entrypoint names dynamic

### ISSUE THREAD

**Issue by mregni** [ldellisola/TraefikKobling#10]
Tried this container today and looks very promising! Not sure if you are open for feature requests and or pull requests?

If so, it would be nice to have dynamic named entrypoint names. You are using "web" and "web-secure" (Workers.cs lines 109 and 110) but I'm using "websecure" so that means I get a fail state in traefik.
<img src="https://user-images.githubusercontent.com/22617019/233834946-0c30781f-6bfb-4586-90b1-492dbccbde1e.png" width="50%">

Would be nice if we can set the names in the yml config file.
If you want, I can make a PR to get it started

**Comment by ldellisola** [comment]
This project is open both to feature requests and specially PRs. 
Definitely go for it!

**Comment by agneevX** [comment]
> Would be nice if we can set the names in the yml config file.

The default entrypoint is named `http`, so this is broken out of the box... also broken if you do not use SSL or an entrypoint named `web-secure`.

**Comment by ldellisola** [comment]
@agneevX I couldn't find any documentation regarding a default entrypoint called http, only traefik. See [here](https://doc.traefik.io/traefik/routing/entrypoints/).

I think all the issues presented here should be solved just by allowing users pass a list of entrypoints names in the config file:
```yml
servers:
  - name: "compute-1"
    apiAddress: http://192.168.0.10:8080
    destinationAddress: http://192.168.0.10
    entryPoints:
      - "web"
      - "websecure"
```

**Comment by agneevX** [comment]
If you do not specify an entrypoint, Traefik creates one for you and calls it `http`.

> I think all the issues presented here should be solved just by allowing users pass a list of entrypoints names in the config file

I think it has to be mapped then? E.g. if you have `http` and `secure` on your main machine and `web` and `web-secure` on your other machines, how will that work?

**Comment by ldellisola** [comment]
A mapping could work, but it still has some issues as entrypoints are not 1-1 mappable. 

For example, I am using the main instance to terminate my tls connection, so there's no equivalent to `web-secure` in the local instances.

I guess it could be updated to something like this:
The main Traefik instance has the following entrypoints:
- `web`
- `web-secure`
- `web-udp`

And the local traefik instance has:
- `local-http`
- `local-udp`

If we want the all http to go to the `local-http` and the udp traffic to go to `local-udp`:
```yml
servers:
  - name: "compute-1"
    apiAddress: http://192.168.0.10:8080
    destinationAddress: http://192.168.0.10
    entryPoints:
      - "web":"local-http"
      - "web-secure":"local-http"
      - "web-udp":"local-udp"
```

Based on the entrypoints in the config, we could say, if the router in the local instance is registered in one of the entrypoints in the left, then we can add the entry point in the right.

For example, if the router in the local instance has the following information:
```json
{
    "Rule": "...",
    "Service":"...",
    "Entrypoints": [
        "local-http"
    ]
}
```
Then on the main instance we can register that router to both the `web` and `web-secure` entrypoints, but not the `web-udp` one.

I'm not sure what the default values should be or if there should be any default values? Maybe the ones that traefik uses on their documentation.

**Comment by agneevX** [comment]
So I tested with:

```yml
...
    entryPoints:
      http: http
```
... since I use the defaults and it still tries to assign routers to non existent entrypoint, breaking the set up:

<img width="326" alt="Screenshot 2023-04-24 at 12 49 24 AM" src="https://user-images.githubusercontent.com/19761269/233860404-b872ff01-771b-4918-83fa-cb81194f3bc7.png">

Also, if the entrypoint is not mentioned in the YAML, would it be possible to create defaults, at least for the default traefik `http` port 80 router?

**Comment by ldellisola** [comment]
The PR closed the issue, I will reopen it.

That's odd, there is not string of `web-secure`in the project now. It shouldn't be using it. Can you try to clean the redis db and restart Kobling?

I will add `http` as the default as well

**Comment by ldellisola** [comment]
@agneevX try the latest `:main` release. It should have support for `http` as the default entrypoint

**Comment by agneevX** [comment]
So yeah the redis persisting stuff between container restarts is weird and unwanted, sorted that.

If I do not mention entrypoints in the kobling config, routers do not show up in traefik.
Only when I mention `http: http` does it show up.

**Comment by agneevX** [comment]
This works well:

```yml
  redis:
    image: redis
    networks: ['proxy']
    tmpfs:
      - /data
```
