### ISSUE TITLE
Random issues with Traefik when Kobling is being used

### ISSUE THREAD

**Issue by agneevX** [ldellisola/TraefikKobling#18]
Hi!

I'm having this issue where some sites fail to load (returns 404) and others fail when something like `/api` is being accessed.

Yet there are no errors on traefik web.

**Comment by ldellisola** [comment]
This may have something to do with broadcasting the `api@internals` routers. 

Can you share your `config.yml` as well as a picture of what routers are enabled in your main traefik instance. I don't need all of them, just the ones that have a `PathPefix` rule. Something similar to this picture:
![Screenshot 2023-04-24 at 12 04 39](https://user-images.githubusercontent.com/26941679/233965710-c7022cb9-1b05-4c39-b595-418c55d838c9.jpg)

**Comment by agneevX** [comment]
Here you go:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/19761269/233972145-8aedd5ed-65f7-4489-b1dc-4b44c02e86de.png">

**Comment by ldellisola** [comment]
Yep, every request with a path that starts with `/api` is being redirected to one both of your instances.
Can you send me your Kobling config and, if you can, the `traefik.yml` for **oracle1** and **oc-bom1**?

**Comment by agneevX** [comment]
```yml
servers:
  - name: "oracle1"
    apiAddress: http://oracle1.tailnet-d10c.ts.net:8090
    destinationAddress: http://oracle1.tailnet-d10c.ts.net:90
```

```yml
  traefik-home:
    container_name: traefik-home
    image: traefik
    restart: unless-stopped
    command:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --entrypoints.http.address=:90
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.oc1.nt`)
    extra_hosts:
      - "host.docker.internal:10.0.0.15"
    ports:
      - 90:90
      - 8090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

It's the same for the other one.

**Comment by ldellisola** [comment]
I can't replicate it on my machine. Here's my setup:
On my local instance:
```yml
services:
  reverse-proxy:
    image: traefik:v2.9
    command: 
      - --accesslog=true
      - --api.insecure=true 
      - --providers.docker=true
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --entrypoints.http.address=:90
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.domain.tld`)
    ports:
      - "90:90"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
```
On the main instance:
```yml
services:
  traefik:
    image: traefik:latest
    ports:
      - 90:90
      - 8090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --accessLog=true
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --entrypoints.http.address=:90
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service" }}.domain.tld`)
      - --providers.redis.endpoints=redis:6379
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
```

I am checking that it works by calling the `whoami` container:
```bash
curl http://localhost:90/api/123 -H 'Host: whoami.lud.ar
```
And it returns the correct response. I can also see the request in the access log of both traefik instances.

Am I missing something here? Can you write a small example that can reproduce the issue?

I could also just add an option to ignore the `api@internal` services. That should solve this issue as well

**Comment by agneevX** [comment]
Along with that, try accessing dozzle on `dozzle.domain.tld`, per the default Docker rule above:

```yml
  dozzle:
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.name: logs
```
