### ISSUE TITLE
Change log level with env variable

### ISSUE THREAD

**Issue by mregni** [ldellisola/TraefikKobling#36]
Hi,

Is there a way to change the log level for the container?

I'm currently running this container
```
  traefik-kobling:
    image: ghcr.io/ldellisola/traefik-kobling:latest
    container_name: traefik-connector
    restart: always
    volumes:
      - /cat/docker/volumes/network_traefik_kobling/config.yml:/config.yml
    environment:
      REDIS_URL: "network_redis:6379"
```

But I get way too many logs, as you can see in the following screenshot. About 222Gb in a month.
![image](https://github.com/ldellisola/TraefikKobling/assets/22617019/a749ddda-1ab5-4266-b872-95da469a7442)

Would be great if there was a LOG_LEVEL: [Info, Warning, Error] env variable.
Or is there another good way to handle the log size?
